apiVersion: v1
kind: Service
metadata:
  name: 'authdenapi'
  labels:
    app: 'authdenapi'
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: 'authdenapi'
